### ISSUE TITLE
Take out from the papers in the `./doc` folder what feature we should be minimally looking at

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/eeg-pain-detection#18]
This information should be distilled and moved to the wiki or the README.md.

@chloesavignac you can write here all the features you think are relevant for the classification given the lliterature. If you can add citation that would be great!

**Comment by chloesavignac** [comment]
Gram et al. 2017 

**Citation**: Gram, M., Erlenwein, J., Petzke, F., Falla, D., Przemeck, M., Emons, M. I., ... & Drewes, A. M. (2017). Prediction of postoperative opioid analgesia using clinical‐experimental parameters and electroencephalography. European Journal of Pain, 21(2), 264-277.

**Features**: Phase-lag index (functional connectivity analysis) + spectral features (delta, theta, alpha, beta), PLI calculated for the same frequency bands 

Used the Neurophysiological Biomarker Toolbox (NBT) (http://www.nbtwiki.net/) to implement the PLI. Divided the signal in time windows, the results for all time windows were averaged. The window width was set to twice the sampling frequency (2000 samples) as this provides a frequency resolution of 0.5 Hz, which is equal to the spectral analysis. The band-pass filter was a 1st order butterworth filter (Lehembre et al., 2012).

**Selection**: the most discriminative features were selected using the criteria for joint mutual information, as this criterion has been found to provide the best selection for data sets with a limited number of samples (Brown et al., 2012)

**Findings**: No differences in PLI between responders and non-responders during rest and during cold pain. (responders to post-operative analgesic treatment with oxycodone and piritramide). Better classification was obtained using solely the delta spectral index from Fp1.

**Comment by chloesavignac** [comment]
@yacineMahdid Do you want the same level of details for articles that only used spectral features ?

**Comment by chloesavignac** [comment]
Brain dysfunction in chronic pain patients assessed by resting-state electroencephalography
**Dinh et al. 2019**

**Citation**: Dinh, S. T., Nickel, M. M., Tiemann, L., May, E. S., Heitmann, H., Hohn, V. D., ... & Gross, J. (2019). Brain dysfunction in chronic pain patients assessed by resting-state electroencephalography. Pain, 160(12), 2751-2765.

**Features**: spectral features + connectivity analysis + graph theory

**Spectral features:**

•	Individual dominant peak frequency (in a range of 6-14 Hz)
•	frequency-specific power topographies between groups using cluster-based permutation tests
•	relative power spectrum. 

**Connectivity analysis:**

Phase-based:
•	Phase locking value (PLV)
citation: Lachaux, J. P., Rodriguez, E., Martinerie, J., & Varela, F. J. (1999). Measuring phase synchrony in brain signals. Human brain mapping, 8(4), 194-208.
•	Debiased weighted phase lag index (dwPLI)
citation: Vinck, M., Oostenveld, R., Van Wingerden, M., Battaglia, F., & Pennartz, C. M. (2011). An improved index of phase-synchronization for electrophysiological data in the presence of volume-conduction, noise and sample-size bias. Neuroimage, 55(4), 1548-1565.
•	Phase-based connectivity is thought to be detached from structure and affected by contextual factors 
citation: Engel, A. K., Gerloff, C., Hilgetag, C. C., & Nolte, G. (2013). Intrinsic coupling modes: multiscale interactions in ongoing brain activity. Neuron, 80(4), 867-886.

Amplitude-based approaches:
•	Orthogonalized amplitude envelope correlation (AEC)
citation: Hipp, J. F., Hawellek, D. J., Corbetta, M., Siegel, M., & Engel, A. K. (2012). Large-scale cortical correlation structure of spontaneous oscillatory activity. Nature neuroscience, 15(6), 884.
•	Amplitude-based connectivity believed to be more related to structural connectivity 
citation: Engel, A. K., Gerloff, C., Hilgetag, C. C., & Nolte, G. (2013). Intrinsic coupling modes: multiscale interactions in ongoing brain activity. Neuron, 80(4), 867-886.

**Graph–theoretical network analysis**

Local analysis: 
•	Degree (number of a node’s edges, ie, the number of connections to other nodes)
citation: Rubinov, M., & Sporns, O. (2010). Complex network measures of brain connectivity: uses and interpretations. Neuroimage, 52(3), 1059-1069.
•	Local CC (the fraction of the node’s neighbors that are also neighbors of each other)
citation: Rubinov, M., & Sporns, O. (2010). Complex network measures of brain connectivity: uses and interpretations. Neuroimage, 52(3), 1059-1069.

Global analysis:
•	global CC (gCC) average of the local CC of all nodes indicating the prevalence of clustered connectivity around individual nodes
citation: Rubinov, M., & Sporns, O. (2010). Complex network measures of brain connectivity: uses and interpretations. Neuroimage, 52(3), 1059-1069.
•	global efficiency (gEff) the inverse of the average shortest path length, represents a measure of functional integration
citation: Rubinov, M., & Sporns, O. (2010). Complex network measures of brain connectivity: uses and interpretations. Neuroimage, 52(3), 1059-1069.
•	small-world-ness (S) describes the ratio of CC and global efficiency and compares it with random networks, can quantify the balance of functional segregation and integration
citation: Rubinov, M., & Sporns, O. (2010). Complex network measures of brain connectivity: uses and interpretations. Neuroimage, 52(3), 1059-1069.
•	Hub disruption index (kd) compares the degree of all nodes with those of a control group
