### ISSUE TITLE
Investigate why some participant throw error when loaded on eeglab

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/eeg-pain-detection#20]
Chloé encountered some error when analysing some participant:
- HE028
-  ME069

![ERROR eeglab](https://user-images.githubusercontent.com/28378576/81083687-e2e9e380-8ec2-11ea-8767-773561d4719f.jpg)

Need to investigate why this occur but not for the other files.

**Comment by yacineMahdid** [comment]
@chloesavignac I think I found why this problem occurs, it seems to be a bug in the biosig or eeglab code for event handling: https://github.com/sccn/eeglab/issues/93
It's been going on for a while though so its hard to find resolution for this. I've tried to make the biosig library from barebone C++, but it's not going to well, I have found a workaround.

1. First download this zip folder and unzip it somewhere at a location that takes precedence over all eeglab files:
[fix_edf_annotation.zip](https://github.com/BIAPT/eeg-pain-detection/files/4603802/fix_edf_annotation.zip)
2. Add this unziped folder to your MATLAB path.
3. launch eeglab and import one problematic files in the usual way. 
4. After you have done cleaning the file you need to close eeglab has for some reason the second time you load a problematic participant the buggy version of the files takes precedence over the new files.
5. Reopen eeglab and go to step 3 to clean the second participant.

This is a workaround however, we need to visually inspect these participant to see if everything is fine with them and with the events. We also need to document that there was some problem with them during the pre-processing, so we should note that down somewhere. You can do so by  creating a report on the wiki: https://github.com/BIAPT/eeg-pain-detection/wiki for now! Let me know if that helped!

**Comment by chloesavignac** [comment]
![image](https://user-images.githubusercontent.com/55591831/81836460-82395700-9511-11ea-9886-35d30cf159a7.png)

@yacineMahdid Thanks for your help. Unfortunately, I am still encountering issues. Maybe it has to do with the location where I saved the folder. Here is a screenshot of my MATLAB path:

**Comment by chloesavignac** [comment]
I also tried to save it under  C:\Program Files\MATLAB\R2017a\toolbox and C:\Program Files\MATLAB\R2017a\toolbox\eeglab14_1_1b but it still crashed.

**Comment by yacineMahdid** [comment]
@chloesavignac I will send you the .set file of the two participant via slack
